spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/eshop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mapper:
  mappers: tk.mybatis.mapper.common.Mapper

dubbo:
  application:
    name: eshop-manage-service
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo